<a href="https://colab.research.google.com/github/paulobezulle/tt/blob/main/LU-pre.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import scipy.linalg as la
np.set_printoptions(precision=2, suppress=True)

In [2]:
def troca_linha(A,e,f):
    A[[e,f],:]=A[[f,e],:]
    #print('troca %d com %d'%(e,f))
def max_in_col (M, pivot_ix):
    nlin=M.shape[0]
    ncol=M.shape[1]
    val = 0
    ix = -1
    for i in range(pivot_ix,nlin):
        if abs(M[i,pivot_ix]) > val:
            val = abs(M[i,pivot_ix])
            ix = i
    return ix

In [7]:
M=np.random.rand(5,5);display(M)
(P, L, U) = la.lu(M)
print(U)
print(P.T)

array([[0.39, 0.45, 0.77, 0.5 , 0.52],
       [0.84, 0.85, 0.56, 0.52, 0.46],
       [0.51, 0.49, 0.68, 0.06, 0.09],
       [0.81, 0.62, 0.07, 0.52, 0.75],
       [0.37, 0.96, 0.66, 0.93, 0.57]])

[[0.84 0.85 0.56 0.52 0.46]
 [0.   0.59 0.42 0.7  0.37]
 [0.   0.   0.47 0.19 0.27]
 [0.   0.   0.   0.39 0.62]
 [0.   0.   0.   0.   0.22]]
[[0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]]


In [11]:
print(L)#@U);print(P.T@M)

[[ 1.    0.    0.    0.    0.  ]
 [ 0.43  1.    0.    0.    0.  ]
 [ 0.46  0.11  1.    0.    0.  ]
 [ 0.97 -0.35 -0.69  1.    0.  ]
 [ 0.6  -0.03  0.76 -0.96  1.  ]]


In [15]:
def lu(A):
    nlin=A.shape[0]
    ncol=A.shape[1]
    I = np.identity(nlin)
    P = np.copy(I)
    L = np.zeros((nlin,nlin))
    print(L)
    U = np.copy(A)
    for pivot_ix in range(0, ncol):
        ix_max = max_in_col(U,pivot_ix)
        if ix_max != pivot_ix:
            troca_linha(U,pivot_ix,ix_max)
            troca_linha(P,pivot_ix,ix_max)
            troca_linha(L,pivot_ix,ix_max)

        pivot = U[pivot_ix, pivot_ix]
        for i in range(pivot_ix+1, nlin):
            cabeca = U[i,pivot_ix]
            L[i,pivot_ix] = cabeca/pivot
            for k in range(pivot_ix, ncol):
                U[i,k] = U[i,k] - U[pivot_ix, k]*cabeca/pivot
    L = L + I
    return P, L, U
(PP,LL,UU)=lu(M)
print(PP)
print(LL)
print(UU)
print(np.allclose(U,UU),np.allclose(P.T,PP))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]]
[[ 1.    0.    0.    0.    0.  ]
 [ 0.43  1.    0.    0.    0.  ]
 [ 0.46  0.11  1.    0.    0.  ]
 [ 0.97 -0.35 -0.69  1.    0.  ]
 [ 0.6  -0.03  0.76 -0.96  1.  ]]
[[ 0.84  0.85  0.56  0.52  0.46]
 [ 0.    0.59  0.42  0.7   0.37]
 [ 0.    0.    0.47  0.19  0.27]
 [-0.    0.    0.    0.39  0.62]
 [ 0.    0.    0.   -0.    0.22]]
True True


In [ ]:
print(P@M)

[[0.39 0.98 0.69 0.47 0.32]
 [0.5  0.08 0.08 0.83 0.22]
 [0.59 0.9  0.7  0.79 0.53]
 [0.6  0.1  0.94 0.82 0.24]
 [0.39 0.73 0.83 0.47 0.79]]


In [ ]:
M

array([[0.41, 0.57, 0.64, 0.47, 1.  , 0.42, 0.53, 0.94, 0.13, 0.7 ],
       [0.97, 0.17, 0.35, 0.24, 0.08, 0.13, 0.52, 0.76, 0.28, 0.57],
       [0.26, 0.46, 0.14, 0.88, 0.31, 0.35, 0.16, 0.86, 0.34, 0.72],
       [0.62, 0.46, 0.6 , 0.08, 0.41, 0.94, 0.42, 0.67, 0.15, 0.41],
       [0.89, 0.47, 0.63, 0.5 , 0.47, 0.3 , 0.19, 0.01, 0.59, 0.65],
       [0.22, 0.37, 0.32, 0.84, 0.87, 0.41, 0.15, 0.27, 0.35, 0.27],
       [0.26, 0.97, 0.75, 0.83, 0.34, 0.67, 0.33, 0.18, 0.24, 0.02],
       [0.46, 0.77, 0.76, 0.04, 0.59, 0.37, 0.41, 0.93, 0.7 , 0.85],
       [0.95, 0.43, 0.56, 0.82, 0.7 , 0.93, 0.71, 0.86, 0.95, 0.04],
       [0.74, 0.97, 0.68, 0.94, 0.04, 0.12, 0.55, 0.19, 0.58, 0.55]])

In [ ]:
def invTI(A):
    lin=A.shape[0]
    col=A.shape[1]
    
    I=np.eye(lin)
    X=np.zeros((lin,lin))

    for j in range(col):
        for i in range(lin):
            soma = 0
            for k in range(i):
                soma = soma + A[i,k]*X[k,j]
            print(I[i,j],-1*soma,A[i,i])
            X[i,j] = (I[i,j] - soma) / A[i,i]
    return X

In [ ]:
def invTS(A):
    lin=A.shape[0]
    col=A.shape[1]
    
    I=np.eye(lin)
    X=np.zeros((lin,lin))

    for j in range(col-1, -1, -1):
        for i in range(lin-1, -1, -1):
            soma = 0
            for k in range(lin-1, i, -1):
                soma = soma + A[i,k]*X[k,j]
            print(I[i,j],-1*soma,A[i,i])
            X[i,j] = (I[i,j] - soma) / A[i,i]
    return X

In [ ]:
A=np.triu(np.random.rand(10,10))

In [ ]:
B = invTS(A)

1.0 0 0.6738170357952293
0.0 -0.8489041671032509 0.08784200443751045
0.0 7.188481401028204 0.3917355826213451
0.0 0.5249890087819034 0.8185259282366645
0.0 -14.471226571850927 0.08555417576768354
0.0 141.67849482141426 0.3159546968757081
0.0 -128.9444704690053 0.1228929678801165
0.0 626.0675917113064 0.33375840608833784
0.0 -868.3601332049151 0.4807198468217475
0.0 516.7731726765961 0.4632992983299238
0.0 0 0.6738170357952293
1.0 -0.0 0.08784200443751045
0.0 -9.483724052986535 0.3917355826213451
0.0 -1.6986773818826375 0.8185259282366645
0.0 19.398664927179894 0.08555417576768354
0.0 -189.69759126938317 0.3159546968757081
0.0 174.15277768277178 0.1228929678801165
0.0 -848.5543599576745 0.33375840608833784
0.0 1180.1011546280397 0.4807198468217475
0.0 -704.2134092171101 0.4632992983299238
0.0 0 0.6738170357952293
0.0 -0.0 0.08784200443751045
1.0 -0.0 0.3917355826213451
0.0 -0.43423776249604423 0.8185259282366645
0.0 -1.711030173814689 0.08555417576768354
0.0 16.50880694525431 0.31595469

In [ ]:
A@B

array([[ 1., -0., -0., -0., -0.,  0.,  0.,  0., -0.,  0.],
       [ 0.,  1.,  0., -0.,  0.,  0.,  0.,  0., -0., -0.],
       [ 0.,  0.,  1., -0., -0.,  0., -0., -0., -0., -0.],
       [ 0.,  0.,  0.,  1., -0.,  0.,  0., -0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1., -0.,  0., -0., -0., -0.],
       [ 0.,  0.,  0.,  0.,  0.,  1., -0.,  0.,  0., -0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1., -0.,  0., -0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0., -0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.]])

In [ ]:
Ainv=la.inv(A)
np.allclose(B,Ainv)

True